# Generated by Django 4.1.4 on 2023-04-24 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applogger', '0002_alter_logentry_options_logentry_action_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='logentry',
            options={'ordering': ['time'], 'verbose_name': 'Действия пользователей', 'verbose_name_plural': 'Действия пользователей '},
        ),
        migrations.RenameField(
            model_name='logentry',
            old_name='message',
            new_name='data',
        ),
        migrations.AddField(
            model_name='logentry',
            name='query',
            field=models.TextField(blank=True, null=True),
        ),
    ]
