# Generated by Django 4.1.4 on 2023-04-25 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applogger', '0003_alter_logentry_options_rename_message_logentry_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='logentry',
            name='description',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='logentry',
            name='object',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='logentry',
            name='action_type',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='logentry',
            name='url',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
