# Generated by Django 4.1.4 on 2023-08-02 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Имя')),
                ('file', models.FileField(blank=True, default='', upload_to='files', verbose_name='Файл')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='Время добавления')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('status', models.CharField(blank=True, choices=[('send', 'Отправлено'), ('process', 'Обрабатывается'), ('ready', 'Готово'), ('error', 'Ошибка')], default='send', max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Запись',
                'verbose_name_plural': 'Записи',
                'ordering': ['-time'],
            },
        ),
    ]
