FROM node:19-alpine
RUN npm install -g nodemon
WORKDIR /app
COPY package.json .
RUN npm install
RUN npm install -g serve
RUN npm install -g env-cmd
COPY . .
ARG REACT_APP_API_URL
RUN chmod 777 create-env-file.sh
RUN sh create-env-file.sh REACT_APP_API_URL=${REACT_APP_API_URL}
RUN npm run build
CMD ["npm", "run","serve"]